<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Operations;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class CreateMessageRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \Openai\SDK\Models\Shared\CreateMessageRequest $createMessageRequest;
    
    /**
     * The ID of the [thread](/docs/api-reference/threads) to create a message for.
     * 
     * @var string $threadId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=thread_id')]
    public string $threadId;
    
	public function __construct()
	{
		$this->createMessageRequest = new \Openai\SDK\Models\Shared\CreateMessageRequest();
		$this->threadId = "";
	}
}
