<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Operations;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class DeleteModelRequest
{
    /**
     * The model to delete
     * 
     * @var string $model
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=model')]
    public string $model;
    
	public function __construct()
	{
		$this->model = "";
	}
}
