<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Operations;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class GetAssistantFileRequest
{
    /**
     * The ID of the assistant who the file belongs to.
     * 
     * @var string $assistantId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=assistant_id')]
    public string $assistantId;
    
    /**
     * The ID of the file we're getting.
     * 
     * @var string $fileId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=file_id')]
    public string $fileId;
    
	public function __construct()
	{
		$this->assistantId = "";
		$this->fileId = "";
	}
}
