<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Operations;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class ListFineTuningEventsRequest
{
    /**
     * Identifier for the last event from the previous pagination request.
     * 
     * @var ?string $after
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=after')]
    public ?string $after = null;
    
    /**
     * The ID of the fine-tuning job to get events for.
     * 
     * 
     * 
     * @var string $fineTuningJobId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=fine_tuning_job_id')]
    public string $fineTuningJobId;
    
    /**
     * Number of events to retrieve.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
	public function __construct()
	{
		$this->after = null;
		$this->fineTuningJobId = "";
		$this->limit = null;
	}
}
