<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Operations;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class RetrieveFineTuneRequest
{
    /**
     * The ID of the fine-tune job
     * 
     * 
     * 
     * @var string $fineTuneId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=fine_tune_id')]
    public string $fineTuneId;
    
	public function __construct()
	{
		$this->fineTuneId = "";
	}
}
