<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Operations;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class SubmitToolOuputsToRunRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \Openai\SDK\Models\Shared\SubmitToolOutputsRunRequest $submitToolOutputsRunRequest;
    
    /**
     * The ID of the run that requires the tool output submission.
     * 
     * @var string $runId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=run_id')]
    public string $runId;
    
    /**
     * The ID of the [thread](/docs/api-reference/threads) to which this run belongs.
     * 
     * @var string $threadId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=thread_id')]
    public string $threadId;
    
	public function __construct()
	{
		$this->submitToolOutputsRunRequest = new \Openai\SDK\Models\Shared\SubmitToolOutputsRunRequest();
		$this->runId = "";
		$this->threadId = "";
	}
}
