<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * AssistantFileObject - A list of [Files](/docs/api-reference/files) attached to an `assistant`.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class AssistantFileObject
{
    /**
     * The assistant ID that the file is attached to.
     * 
     * @var string $assistantId
     */
	#[\JMS\Serializer\Annotation\SerializedName('assistant_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $assistantId;
    
    /**
     * The Unix timestamp (in seconds) for when the assistant file was created.
     * 
     * @var int $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
    /**
     * The identifier, which can be referenced in API endpoints.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The object type, which is always `assistant.file`.
     * 
     * @var \Openai\SDK\Models\Shared\Object $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\Object>')]
    public Object $object;
    
	public function __construct()
	{
		$this->assistantId = "";
		$this->createdAt = 0;
		$this->id = "";
		$this->object = \Openai\SDK\Models\Shared\Object::AssistantFile;
	}
}
