<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * CategoryScores - A list of the categories along with their scores as predicted by model.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class CategoryScores
{
    /**
     * The score for the category 'harassment'.
     * 
     * @var float $harassment
     */
	#[\JMS\Serializer\Annotation\SerializedName('harassment')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $harassment;
    
    /**
     * The score for the category 'harassment/threatening'.
     * 
     * @var float $harassmentThreatening
     */
	#[\JMS\Serializer\Annotation\SerializedName('harassment/threatening')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $harassmentThreatening;
    
    /**
     * The score for the category 'hate'.
     * 
     * @var float $hate
     */
	#[\JMS\Serializer\Annotation\SerializedName('hate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $hate;
    
    /**
     * The score for the category 'hate/threatening'.
     * 
     * @var float $hateThreatening
     */
	#[\JMS\Serializer\Annotation\SerializedName('hate/threatening')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $hateThreatening;
    
    /**
     * The score for the category 'self-harm'.
     * 
     * @var float $selfHarm
     */
	#[\JMS\Serializer\Annotation\SerializedName('self-harm')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $selfHarm;
    
    /**
     * The score for the category 'self-harm/instructions'.
     * 
     * @var float $selfHarmInstructions
     */
	#[\JMS\Serializer\Annotation\SerializedName('self-harm/instructions')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $selfHarmInstructions;
    
    /**
     * The score for the category 'self-harm/intent'.
     * 
     * @var float $selfHarmIntent
     */
	#[\JMS\Serializer\Annotation\SerializedName('self-harm/intent')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $selfHarmIntent;
    
    /**
     * The score for the category 'sexual'.
     * 
     * @var float $sexual
     */
	#[\JMS\Serializer\Annotation\SerializedName('sexual')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $sexual;
    
    /**
     * The score for the category 'sexual/minors'.
     * 
     * @var float $sexualMinors
     */
	#[\JMS\Serializer\Annotation\SerializedName('sexual/minors')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $sexualMinors;
    
    /**
     * The score for the category 'violence'.
     * 
     * @var float $violence
     */
	#[\JMS\Serializer\Annotation\SerializedName('violence')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $violence;
    
    /**
     * The score for the category 'violence/graphic'.
     * 
     * @var float $violenceGraphic
     */
	#[\JMS\Serializer\Annotation\SerializedName('violence/graphic')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $violenceGraphic;
    
	public function __construct()
	{
		$this->harassment = 0;
		$this->harassmentThreatening = 0;
		$this->hate = 0;
		$this->hateThreatening = 0;
		$this->selfHarm = 0;
		$this->selfHarmInstructions = 0;
		$this->selfHarmIntent = 0;
		$this->sexual = 0;
		$this->sexualMinors = 0;
		$this->violence = 0;
		$this->violenceGraphic = 0;
	}
}
