<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * Categories - A list of the categories, and whether they are flagged or not.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class Categories
{
    /**
     * Content that expresses, incites, or promotes harassing language towards any target.
     * 
     * @var bool $harassment
     */
	#[\JMS\Serializer\Annotation\SerializedName('harassment')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $harassment;
    
    /**
     * Harassment content that also includes violence or serious harm towards any target.
     * 
     * @var bool $harassmentThreatening
     */
	#[\JMS\Serializer\Annotation\SerializedName('harassment/threatening')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $harassmentThreatening;
    
    /**
     * Content that expresses, incites, or promotes hate based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste. Hateful content aimed at non-protected groups (e.g., chess players) is harassment.
     * 
     * @var bool $hate
     */
	#[\JMS\Serializer\Annotation\SerializedName('hate')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $hate;
    
    /**
     * Hateful content that also includes violence or serious harm towards the targeted group based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste.
     * 
     * @var bool $hateThreatening
     */
	#[\JMS\Serializer\Annotation\SerializedName('hate/threatening')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $hateThreatening;
    
    /**
     * Content that promotes, encourages, or depicts acts of self-harm, such as suicide, cutting, and eating disorders.
     * 
     * @var bool $selfHarm
     */
	#[\JMS\Serializer\Annotation\SerializedName('self-harm')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $selfHarm;
    
    /**
     * Content that encourages performing acts of self-harm, such as suicide, cutting, and eating disorders, or that gives instructions or advice on how to commit such acts.
     * 
     * @var bool $selfHarmInstructions
     */
	#[\JMS\Serializer\Annotation\SerializedName('self-harm/instructions')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $selfHarmInstructions;
    
    /**
     * Content where the speaker expresses that they are engaging or intend to engage in acts of self-harm, such as suicide, cutting, and eating disorders.
     * 
     * @var bool $selfHarmIntent
     */
	#[\JMS\Serializer\Annotation\SerializedName('self-harm/intent')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $selfHarmIntent;
    
    /**
     * Content meant to arouse sexual excitement, such as the description of sexual activity, or that promotes sexual services (excluding sex education and wellness).
     * 
     * @var bool $sexual
     */
	#[\JMS\Serializer\Annotation\SerializedName('sexual')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $sexual;
    
    /**
     * Sexual content that includes an individual who is under 18 years old.
     * 
     * @var bool $sexualMinors
     */
	#[\JMS\Serializer\Annotation\SerializedName('sexual/minors')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $sexualMinors;
    
    /**
     * Content that depicts death, violence, or physical injury.
     * 
     * @var bool $violence
     */
	#[\JMS\Serializer\Annotation\SerializedName('violence')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $violence;
    
    /**
     * Content that depicts death, violence, or physical injury in graphic detail.
     * 
     * @var bool $violenceGraphic
     */
	#[\JMS\Serializer\Annotation\SerializedName('violence/graphic')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $violenceGraphic;
    
	public function __construct()
	{
		$this->harassment = false;
		$this->harassmentThreatening = false;
		$this->hate = false;
		$this->hateThreatening = false;
		$this->selfHarm = false;
		$this->selfHarmInstructions = false;
		$this->selfHarmIntent = false;
		$this->sexual = false;
		$this->sexualMinors = false;
		$this->violence = false;
		$this->violenceGraphic = false;
	}
}
