<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The role of the author of this message. */
enum ChatCompletionResponseMessageRole: string
{
    case System = 'system';
    case User = 'user';
    case Assistant = 'assistant';
}
