<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * ChatCompletionResponseMessage - A chat completion message generated by the model.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class ChatCompletionResponseMessage
{
    /**
     * The contents of the message.
     * 
     * @var string $content
     */
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $content;
    
    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     * 
     * @var ?\Openai\SDK\Models\Shared\FunctionCall $functionCall
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
	#[\JMS\Serializer\Annotation\SerializedName('function_call')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\FunctionCall')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?FunctionCall $functionCall = null;
    
    /**
     * The role of the author of this message.
     * 
     * @var \Openai\SDK\Models\Shared\Role $role
     */
	#[\JMS\Serializer\Annotation\SerializedName('role')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\Role>')]
    public Role $role;
    
    /**
     * The tool calls generated by the model, such as function calls.
     * 
     * @var ?array<\Openai\SDK\Models\Shared\ChatCompletionMessageToolCall> $toolCalls
     */
	#[\JMS\Serializer\Annotation\SerializedName('tool_calls')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\ChatCompletionMessageToolCall>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $toolCalls = null;
    
	public function __construct()
	{
		$this->content = "";
		$this->functionCall = null;
		$this->role = \Openai\SDK\Models\Shared\Role::Assistant;
		$this->toolCalls = null;
	}
}
