<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * ChatCompletionRequestMessageFunctionCall - The name and arguments of a function that should be called, as generated by the model.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class ChatCompletionRequestMessageFunctionCall
{
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     * 
     * @var ?string $arguments
     */
	#[\JMS\Serializer\Annotation\SerializedName('arguments')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $arguments = null;
    
    /**
     * The name of the function to call.
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
	public function __construct()
	{
		$this->arguments = null;
		$this->name = null;
	}
}
