<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class ChatCompletionRequestMessage
{
    /**
     * The contents of the message
     * 
     * @var string $content
     */
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $content;
    
    /**
     * The name of the user in a multi-user chat
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * The role of the author of this message.
     * 
     * @var \Openai\SDK\Models\Shared\ChatCompletionRequestMessageRole $role
     */
	#[\JMS\Serializer\Annotation\SerializedName('role')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\ChatCompletionRequestMessageRole>')]
    public ChatCompletionRequestMessageRole $role;
    
	public function __construct()
	{
		$this->content = "";
		$this->name = null;
		$this->role = \Openai\SDK\Models\Shared\ChatCompletionRequestMessageRole::System;
	}
}
