<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class ChatCompletionResponseMessage
{
    /**
     * The contents of the message
     * 
     * @var string $content
     */
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $content;
    
    /**
     * The role of the author of this message.
     * 
     * @var \Openai\SDK\Models\Shared\ChatCompletionResponseMessageRoleEnum $role
     */
	#[\JMS\Serializer\Annotation\SerializedName('role')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\ChatCompletionResponseMessageRoleEnum>')]
    public ChatCompletionResponseMessageRoleEnum $role;
    
	public function __construct()
	{
		$this->content = "";
		$this->role = \Openai\SDK\Models\Shared\ChatCompletionResponseMessageRoleEnum::SYSTEM;
	}
}
