<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class ChatCompletionMessageToolCall
{
    /**
     * The function that the model called.
     * 
     * @var \Openai\SDK\Models\Shared\FunctionT $function
     */
	#[\JMS\Serializer\Annotation\SerializedName('function')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\FunctionT')]
    public FunctionT $function;
    
    /**
     * The ID of the tool call.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The type of the tool. Currently, only `function` is supported.
     * 
     * @var \Openai\SDK\Models\Shared\Type $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\Type>')]
    public Type $type;
    
	public function __construct()
	{
		$this->function = new \Openai\SDK\Models\Shared\FunctionT();
		$this->id = "";
		$this->type = \Openai\SDK\Models\Shared\Type::Function;
	}
}
