<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** One of `server_error`, `rate_limit_exceeded`, or `invalid_prompt`. */
enum Code: string
{
    case ServerError = 'server_error';
    case RateLimitExceeded = 'rate_limit_exceeded';
    case InvalidPrompt = 'invalid_prompt';
}
