<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class CreateChatCompletionResponseChoices
{
	#[\JMS\Serializer\Annotation\SerializedName('finish_reason')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\CreateChatCompletionResponseChoicesFinishReason>')]
    public CreateChatCompletionResponseChoicesFinishReason $finishReason;
    
	#[\JMS\Serializer\Annotation\SerializedName('index')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $index;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\ChatCompletionResponseMessage')]
    public ChatCompletionResponseMessage $message;
    
	public function __construct()
	{
		$this->finishReason = \Openai\SDK\Models\Shared\CreateChatCompletionResponseChoicesFinishReason::Stop;
		$this->index = 0;
		$this->message = new \Openai\SDK\Models\Shared\ChatCompletionResponseMessage();
	}
}
