<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`. */
enum CreateImageEditRequestSize: string
{
    case TwoHundredAndFiftySixx256 = '256x256';
    case FiveHundredAndTwelvex512 = '512x512';
    case OneThousandAndTwentyFourx1024 = '1024x1024';
}
