<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * CreateModerationResponse - Represents policy compliance report by OpenAI's content moderation model against a given input.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class CreateModerationResponse
{
    /**
     * The unique identifier for the moderation request.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The model used to generate the moderation results.
     * 
     * @var string $model
     */
	#[\JMS\Serializer\Annotation\SerializedName('model')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $model;
    
    /**
     * A list of moderation objects.
     * 
     * @var array<\Openai\SDK\Models\Shared\Results> $results
     */
	#[\JMS\Serializer\Annotation\SerializedName('results')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\Results>')]
    public array $results;
    
	public function __construct()
	{
		$this->id = "";
		$this->model = "";
		$this->results = [];
	}
}
