<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class CreateImageEditRequest
{
    /**
     * The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask.
     * 
     * @var \Openai\SDK\Models\Shared\CreateImageEditRequestImage $image
     */
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public CreateImageEditRequestImage $image;
    
    /**
     * An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`.
     * 
     * @var ?\Openai\SDK\Models\Shared\CreateImageEditRequestMask $mask
     */
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public ?CreateImageEditRequestMask $mask = null;
    
	#[SpeakeasyMetadata('multipartForm:name=n')]
    public mixed $n = null;
    
    /**
     * A text description of the desired image(s). The maximum length is 1000 characters.
     * 
     * @var string $prompt
     */
	#[SpeakeasyMetadata('multipartForm:name=prompt')]
    public string $prompt;
    
	#[SpeakeasyMetadata('multipartForm:name=response_format')]
    public mixed $responseFormat = null;
    
	#[SpeakeasyMetadata('multipartForm:name=size')]
    public mixed $size = null;
    
	#[SpeakeasyMetadata('multipartForm:name=user')]
    public mixed $user = null;
    
	public function __construct()
	{
		$this->image = new \Openai\SDK\Models\Shared\CreateImageEditRequestImage();
		$this->mask = null;
		$this->n = null;
		$this->prompt = "";
		$this->responseFormat = null;
		$this->size = null;
		$this->user = null;
	}
}
