<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * The name of the base model to fine-tune. You can select one of "ada",
 * 
 * "babbage", "curie", "davinci", or a fine-tuned model created after 2022-04-21 and before 2023-08-22.
 * To learn more about these models, see the
 * [Models](/docs/models) documentation.
 * 
 */
enum CreateFineTuneRequestModel2: string
{
    case Ada = 'ada';
    case Babbage = 'babbage';
    case Curie = 'curie';
    case Davinci = 'davinci';
}
