<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class CreateEmbeddingResponse
{
    /**
     * The list of embeddings generated by the model.
     * 
     * @var array<\Openai\SDK\Models\Shared\Embedding> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\Embedding>')]
    public array $data;
    
    /**
     * The name of the model used to generate the embedding.
     * 
     * @var string $model
     */
	#[\JMS\Serializer\Annotation\SerializedName('model')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $model;
    
    /**
     * The object type, which is always "embedding".
     * 
     * @var string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $object;
    
    /**
     * The usage information for the request.
     * 
     * @var \Openai\SDK\Models\Shared\CreateEmbeddingResponseUsage $usage
     */
	#[\JMS\Serializer\Annotation\SerializedName('usage')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\CreateEmbeddingResponseUsage')]
    public CreateEmbeddingResponseUsage $usage;
    
	public function __construct()
	{
		$this->data = [];
		$this->model = "";
		$this->object = "";
		$this->usage = new \Openai\SDK\Models\Shared\CreateEmbeddingResponseUsage();
	}
}
