<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class CreateSpeechRequest
{
    /**
     * The text to generate audio for. The maximum length is 4096 characters.
     * 
     * @var string $input
     */
	#[\JMS\Serializer\Annotation\SerializedName('input')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $input;
    
    /**
     * One of the available [TTS models](/docs/models/tts): `tts-1` or `tts-1-hd`
     * 
     * 
     * 
     * @var mixed $model
     */
	#[\JMS\Serializer\Annotation\SerializedName('model')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $model;
    
    /**
     * The format to audio in. Supported formats are `mp3`, `opus`, `aac`, and `flac`.
     * 
     * @var ?\Openai\SDK\Models\Shared\CreateSpeechRequestResponseFormat $responseFormat
     */
	#[\JMS\Serializer\Annotation\SerializedName('response_format')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\CreateSpeechRequestResponseFormat>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateSpeechRequestResponseFormat $responseFormat = null;
    
    /**
     * The speed of the generated audio. Select a value from `0.25` to `4.0`. `1.0` is the default.
     * 
     * @var ?float $speed
     */
	#[\JMS\Serializer\Annotation\SerializedName('speed')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $speed = null;
    
    /**
     * The voice to use when generating the audio. Supported voices are `alloy`, `echo`, `fable`, `onyx`, `nova`, and `shimmer`.
     * 
     * @var \Openai\SDK\Models\Shared\Voice $voice
     */
	#[\JMS\Serializer\Annotation\SerializedName('voice')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\Voice>')]
    public Voice $voice;
    
	public function __construct()
	{
		$this->input = "";
		$this->model = null;
		$this->responseFormat = null;
		$this->speed = null;
		$this->voice = \Openai\SDK\Models\Shared\Voice::Alloy;
	}
}
