<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The format to return the embeddings in. Can be either `float` or [`base64`](https://pypi.org/project/pybase64/). */
enum CreateEmbeddingRequestEncodingFormat: string
{
    case Float = 'float';
    case Base64 = 'base64';
}
