<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * CreateChatCompletionResponse - Represents a chat completion response returned by model, based on the provided input.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class CreateChatCompletionResponse
{
    /**
     * A list of chat completion choices. Can be more than one if `n` is greater than 1.
     * 
     * @var array<\Openai\SDK\Models\Shared\Choices> $choices
     */
	#[\JMS\Serializer\Annotation\SerializedName('choices')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\Choices>')]
    public array $choices;
    
    /**
     * The Unix timestamp (in seconds) of when the chat completion was created.
     * 
     * @var int $created
     */
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $created;
    
    /**
     * A unique identifier for the chat completion.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The model used for the chat completion.
     * 
     * @var string $model
     */
	#[\JMS\Serializer\Annotation\SerializedName('model')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $model;
    
    /**
     * The object type, which is always `chat.completion`.
     * 
     * @var \Openai\SDK\Models\Shared\CreateChatCompletionResponseObject $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\CreateChatCompletionResponseObject>')]
    public CreateChatCompletionResponseObject $object;
    
    /**
     * This fingerprint represents the backend configuration that the model runs with.
     * 
     * 
     * Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.
     * 
     * 
     * @var ?string $systemFingerprint
     */
	#[\JMS\Serializer\Annotation\SerializedName('system_fingerprint')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $systemFingerprint = null;
    
    /**
     * Usage statistics for the completion request.
     * 
     * @var ?\Openai\SDK\Models\Shared\CompletionUsage $usage
     */
	#[\JMS\Serializer\Annotation\SerializedName('usage')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\CompletionUsage')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CompletionUsage $usage = null;
    
	public function __construct()
	{
		$this->choices = [];
		$this->created = 0;
		$this->id = "";
		$this->model = "";
		$this->object = \Openai\SDK\Models\Shared\CreateChatCompletionResponseObject::ChatCompletion;
		$this->systemFingerprint = null;
		$this->usage = null;
	}
}
