<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * ID of the model to use. Only `whisper-1` is currently available.
 * 
 * 
 */
enum CreateTranslationRequestModel2: string
{
    case Whisper1 = 'whisper-1';
}
