<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class CreateImageRequest
{
    /**
     * The number of images to generate. Must be between 1 and 10.
     * 
     * @var ?int $n
     */
	#[\JMS\Serializer\Annotation\SerializedName('n')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $n = null;
    
    /**
     * A text description of the desired image(s). The maximum length is 1000 characters.
     * 
     * @var string $prompt
     */
	#[\JMS\Serializer\Annotation\SerializedName('prompt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $prompt;
    
    /**
     * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
     * 
     * @var ?\Openai\SDK\Models\Shared\CreateImageRequestResponseFormat $responseFormat
     */
	#[\JMS\Serializer\Annotation\SerializedName('response_format')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\CreateImageRequestResponseFormat>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateImageRequestResponseFormat $responseFormat = null;
    
    /**
     * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     * 
     * @var ?\Openai\SDK\Models\Shared\CreateImageRequestSize $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\CreateImageRequestSize>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateImageRequestSize $size = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $user = null;
    
	public function __construct()
	{
		$this->n = null;
		$this->prompt = "";
		$this->responseFormat = null;
		$this->size = null;
		$this->user = null;
	}
}
