<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;

use \Openai\SDK\Utils\SpeakeasyMetadata;
class CreateFileRequest
{
    /**
     * Name of the [JSON Lines](https://jsonlines.readthedocs.io/en/latest/) file to be uploaded.
     * 
     * 
     * If the `purpose` is set to "fine-tune", the file will be used for fine-tuning.
     * 
     * 
     * @var \Openai\SDK\Models\Shared\CreateFileRequestFile $file
     */
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public CreateFileRequestFile $file;
    
    /**
     * The intended purpose of the uploaded documents.
     * 
     * 
     * Use "fine-tune" for [fine-tuning](/docs/api-reference/fine-tuning). This allows us to validate the format of the uploaded file.
     * 
     * 
     * @var string $purpose
     */
	#[SpeakeasyMetadata('multipartForm:name=purpose')]
    public string $purpose;
    
	public function __construct()
	{
		$this->file = new \Openai\SDK\Models\Shared\CreateFileRequestFile();
		$this->purpose = "";
	}
}
