<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * The name of the model to fine-tune. You can select one of the
 * 
 * [supported models](/docs/guides/fine-tuning/what-models-can-be-fine-tuned).
 * 
 */
enum CreateFineTuningJobRequestModel2: string
{
    case Babbage002 = 'babbage-002';
    case Davinci002 = 'davinci-002';
    case Gpt35Turbo = 'gpt-3.5-turbo';
}
