<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * CreateEditResponse - OK
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 * @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
class CreateEditResponse
{
    /**
     * A list of edit choices. Can be more than one if `n` is greater than 1.
     * 
     * @var array<\Openai\SDK\Models\Shared\CreateEditResponseChoices> $choices
     */
	#[\JMS\Serializer\Annotation\SerializedName('choices')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\CreateEditResponseChoices>')]
    public array $choices;
    
    /**
     * The Unix timestamp (in seconds) of when the edit was created.
     * 
     * @var int $created
     */
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $created;
    
    /**
     * The object type, which is always `edit`.
     * 
     * @var string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $object;
    
    /**
     * Usage statistics for the completion request.
     * 
     * @var \Openai\SDK\Models\Shared\CompletionUsage $usage
     */
	#[\JMS\Serializer\Annotation\SerializedName('usage')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\CompletionUsage')]
    public CompletionUsage $usage;
    
	public function __construct()
	{
		$this->choices = [];
		$this->created = 0;
		$this->object = "";
		$this->usage = new \Openai\SDK\Models\Shared\CompletionUsage();
	}
}
