<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt.
 * 
 * 
 */
enum CreateTranscriptionRequestResponseFormat: string
{
    case Json = 'json';
    case Text = 'text';
    case Srt = 'srt';
    case VerboseJson = 'verbose_json';
    case Vtt = 'vtt';
}
