<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The role of the entity that is creating the message. Currently only `user` is supported. */
enum CreateMessageRequestRole: string
{
    case User = 'user';
}
