<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class CreateAssistantFileRequest
{
    /**
     * A [File](/docs/api-reference/files) ID (with `purpose="assistants"`) that the assistant should use. Useful for tools like `retrieval` and `code_interpreter` that can access files.
     * 
     * @var string $fileId
     */
	#[\JMS\Serializer\Annotation\SerializedName('file_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $fileId;
    
	public function __construct()
	{
		$this->fileId = "";
	}
}
