<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * Embedding - Represents an embedding vector returned by embedding endpoint.
 * 
 * 
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class Embedding
{
    /**
     * The embedding vector, which is a list of floats. The length of vector depends on the model as listed in the [embedding guide](/docs/guides/embeddings).
     * 
     * 
     * 
     * @var array<float> $embedding
     */
	#[\JMS\Serializer\Annotation\SerializedName('embedding')]
    #[\JMS\Serializer\Annotation\Type('array<float>')]
    public array $embedding;
    
    /**
     * The index of the embedding in the list of embeddings.
     * 
     * @var int $index
     */
	#[\JMS\Serializer\Annotation\SerializedName('index')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $index;
    
    /**
     * The object type, which is always "embedding".
     * 
     * @var \Openai\SDK\Models\Shared\EmbeddingObject $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\EmbeddingObject>')]
    public EmbeddingObject $object;
    
	public function __construct()
	{
		$this->embedding = [];
		$this->index = 0;
		$this->object = \Openai\SDK\Models\Shared\EmbeddingObject::Embedding;
	}
}
