<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset.
 * 
 * "auto" decides the optimal number of epochs based on the size of the dataset. If setting the number manually, we support any number between 1 and 50 epochs.
 */
enum FineTuningJobHyperparametersNEpochs1: string
{
    case Auto = 'auto';
}
