<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


enum FineTuningJobEventObject: string
{
    case FineTuningJobEvent = 'fine_tuning.job.event';
}
