<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * FineTuningJobEvent - Fine-tuning job event object
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class FineTuningJobEvent
{
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('level')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\Level>')]
    public Level $level;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\FineTuningJobEventObject>')]
    public FineTuningJobEventObject $object;
    
	public function __construct()
	{
		$this->createdAt = 0;
		$this->id = "";
		$this->level = \Openai\SDK\Models\Shared\Level::Info;
		$this->message = "";
		$this->object = \Openai\SDK\Models\Shared\FineTuningJobEventObject::FineTuningJobEvent;
	}
}
