<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * FineTuningJobError - For fine-tuning jobs that have `failed`, this will contain more information on the cause of the failure.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class FineTuningJobError
{
    /**
     * A machine-readable error code.
     * 
     * @var ?string $code
     */
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $code = null;
    
    /**
     * A human-readable error message.
     * 
     * @var ?string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $message = null;
    
    /**
     * The parameter that was invalid, usually `training_file` or `validation_file`. This field will be null if the failure was not parameter-specific.
     * 
     * @var ?string $param
     */
	#[\JMS\Serializer\Annotation\SerializedName('param')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $param = null;
    
	public function __construct()
	{
		$this->code = null;
		$this->message = null;
		$this->param = null;
	}
}
