<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * FineTuningJobHyperparameters - The hyperparameters used for the fine-tuning job. See the [fine-tuning guide](/docs/guides/fine-tuning) for more details.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class FineTuningJobHyperparameters
{
    /**
     * The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset.
     * 
     * "auto" decides the optimal number of epochs based on the size of the dataset. If setting the number manually, we support any number between 1 and 50 epochs.
     * 
     * @var mixed $nEpochs
     */
	#[\JMS\Serializer\Annotation\SerializedName('n_epochs')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $nEpochs;
    
	public function __construct()
	{
		$this->nEpochs = null;
	}
}
