<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * IncompleteDetails - On an incomplete message, details about why the message is incomplete.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class IncompleteDetails
{
    /**
     * The reason the message is incomplete.
     * 
     * @var \Openai\SDK\Models\Shared\Reason $reason
     */
	#[\JMS\Serializer\Annotation\SerializedName('reason')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\Reason>')]
    public Reason $reason;
    
	public function __construct()
	{
		$this->reason = \Openai\SDK\Models\Shared\Reason::ContentFilter;
	}
}
