<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class ListModelsResponse
{
    /**
     * $data
     * 
     * @var array<\Openai\SDK\Models\Shared\Model> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\Model>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\ListModelsResponseObject>')]
    public ListModelsResponseObject $object;
    
	public function __construct()
	{
		$this->data = [];
		$this->object = \Openai\SDK\Models\Shared\ListModelsResponseObject::List;
	}
}
