<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


enum ListPaginatedFineTuningJobsResponseObject: string
{
    case List = 'list';
}
