<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * Logprobs - Log probability information for the choice.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class Logprobs
{
    /**
     * A list of message content tokens with log probability information.
     * 
     * @var array<\Openai\SDK\Models\Shared\Content> $content
     */
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('array<Openai\SDK\Models\Shared\Content>')]
    public array $content;
    
	public function __construct()
	{
		$this->content = [];
	}
}
