<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The object type, which is always `thread.message.file`. */
enum MessageFileObjectObject: string
{
    case ThreadMessageFile = 'thread.message.file';
}
