<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * MessageFileObject - A list of files attached to a `message`.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class MessageFileObject
{
    /**
     * The Unix timestamp (in seconds) for when the message file was created.
     * 
     * @var int $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
    /**
     * The identifier, which can be referenced in API endpoints.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The ID of the [message](/docs/api-reference/messages) that the [File](/docs/api-reference/files) is attached to.
     * 
     * @var string $messageId
     */
	#[\JMS\Serializer\Annotation\SerializedName('message_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $messageId;
    
    /**
     * The object type, which is always `thread.message.file`.
     * 
     * @var \Openai\SDK\Models\Shared\MessageFileObjectObject $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\MessageFileObjectObject>')]
    public MessageFileObjectObject $object;
    
	public function __construct()
	{
		$this->createdAt = 0;
		$this->id = "";
		$this->messageId = "";
		$this->object = \Openai\SDK\Models\Shared\MessageFileObjectObject::ThreadMessageFile;
	}
}
