<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * OpenAIFile - OK
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class OpenAIFile
{
	#[\JMS\Serializer\Annotation\SerializedName('bytes')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $bytes;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('filename')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $filename;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $object;
    
	#[\JMS\Serializer\Annotation\SerializedName('purpose')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $purpose;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $status = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status_details')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\OpenAIFileStatusDetails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OpenAIFileStatusDetails $statusDetails = null;
    
	public function __construct()
	{
		$this->bytes = 0;
		$this->createdAt = 0;
		$this->filename = "";
		$this->id = "";
		$this->object = "";
		$this->purpose = "";
		$this->status = null;
		$this->statusDetails = null;
	}
}
