<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * OpenAIFile - The `File` object represents a document that has been uploaded to OpenAI.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class OpenAIFile
{
    /**
     * The size of the file, in bytes.
     * 
     * @var int $bytes
     */
	#[\JMS\Serializer\Annotation\SerializedName('bytes')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $bytes;
    
    /**
     * The Unix timestamp (in seconds) for when the file was created.
     * 
     * @var int $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
    /**
     * The name of the file.
     * 
     * @var string $filename
     */
	#[\JMS\Serializer\Annotation\SerializedName('filename')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $filename;
    
    /**
     * The file identifier, which can be referenced in the API endpoints.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The object type, which is always `file`.
     * 
     * @var \Openai\SDK\Models\Shared\OpenAIFileObject $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\OpenAIFileObject>')]
    public OpenAIFileObject $object;
    
    /**
     * The intended purpose of the file. Supported values are `fine-tune`, `fine-tune-results`, `assistants`, and `assistants_output`.
     * 
     * @var \Openai\SDK\Models\Shared\OpenAIFilePurpose $purpose
     */
	#[\JMS\Serializer\Annotation\SerializedName('purpose')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\OpenAIFilePurpose>')]
    public OpenAIFilePurpose $purpose;
    
    /**
     * Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`.
     * 
     * @var \Openai\SDK\Models\Shared\OpenAIFileStatus $status
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\OpenAIFileStatus>')]
    public OpenAIFileStatus $status;
    
    /**
     * Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`.
     * 
     * @var ?string $statusDetails
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
	#[\JMS\Serializer\Annotation\SerializedName('status_details')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $statusDetails = null;
    
	public function __construct()
	{
		$this->bytes = 0;
		$this->createdAt = 0;
		$this->filename = "";
		$this->id = "";
		$this->object = \Openai\SDK\Models\Shared\OpenAIFileObject::File;
		$this->purpose = \Openai\SDK\Models\Shared\OpenAIFilePurpose::FineTune;
		$this->status = \Openai\SDK\Models\Shared\OpenAIFileStatus::Uploaded;
		$this->statusDetails = null;
	}
}
