<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * ResponseFormat - An object specifying the format that the model must output. Used to enable JSON mode.
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class ResponseFormat
{
    /**
     * Setting to `json_object` enables JSON mode. This guarantees that the message the model generates is valid JSON. 
     * 
     * 
     * Note that your system prompt must still instruct the model to produce JSON, and to help ensure you don't forget, the API will throw an error if the string `JSON` does not appear in your system message. Also note that the message content may be partial (i.e. cut off) if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length. 
     * 
     * Must be one of `text` or `json_object`.
     * 
     * 
     * @var ?\Openai\SDK\Models\Shared\CreateChatCompletionRequestType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\CreateChatCompletionRequestType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateChatCompletionRequestType $type = null;
    
	public function __construct()
	{
		$this->type = null;
	}
}
