<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The status of the run, which can be either `in_progress`, `cancelled`, `failed`, `completed`, or `expired`. */
enum RunStepObjectStatus: string
{
    case InProgress = 'in_progress';
    case Cancelled = 'cancelled';
    case Failed = 'failed';
    case Completed = 'completed';
    case Expired = 'expired';
}
