<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * RunStepObject - Represents a step in execution of a run.
 * 
 * 
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class RunStepObject
{
    /**
     * The ID of the [assistant](/docs/api-reference/assistants) associated with the run step.
     * 
     * @var string $assistantId
     */
	#[\JMS\Serializer\Annotation\SerializedName('assistant_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $assistantId;
    
    /**
     * The Unix timestamp (in seconds) for when the run step was cancelled.
     * 
     * @var int $cancelledAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('cancelled_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $cancelledAt;
    
    /**
     * The Unix timestamp (in seconds) for when the run step completed.
     * 
     * @var int $completedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('completed_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $completedAt;
    
    /**
     * The Unix timestamp (in seconds) for when the run step was created.
     * 
     * @var int $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
    /**
     * The Unix timestamp (in seconds) for when the run step expired. A step is considered expired if the parent run is expired.
     * 
     * @var int $expiredAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('expired_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $expiredAt;
    
    /**
     * The Unix timestamp (in seconds) for when the run step failed.
     * 
     * @var int $failedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('failed_at')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $failedAt;
    
    /**
     * The identifier of the run step, which can be referenced in API endpoints.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The last error associated with this run step. Will be `null` if there are no errors.
     * 
     * @var \Openai\SDK\Models\Shared\RunStepObjectLastError $lastError
     */
	#[\JMS\Serializer\Annotation\SerializedName('last_error')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\RunStepObjectLastError')]
    public RunStepObjectLastError $lastError;
    
    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
     * 
     * 
     * 
     * @var \Openai\SDK\Models\Shared\RunStepObjectMetadata $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\RunStepObjectMetadata')]
    public RunStepObjectMetadata $metadata;
    
    /**
     * The object type, which is always `assistant.run.step``.
     * 
     * @var \Openai\SDK\Models\Shared\RunStepObjectObject $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\RunStepObjectObject>')]
    public RunStepObjectObject $object;
    
    /**
     * The ID of the [run](/docs/api-reference/runs) that this run step is a part of.
     * 
     * @var string $runId
     */
	#[\JMS\Serializer\Annotation\SerializedName('run_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $runId;
    
    /**
     * The status of the run, which can be either `in_progress`, `cancelled`, `failed`, `completed`, or `expired`.
     * 
     * @var \Openai\SDK\Models\Shared\RunStepObjectStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\RunStepObjectStatus>')]
    public RunStepObjectStatus $status;
    
    /**
     * The details of the run step.
     * 
     * @var mixed $stepDetails
     */
	#[\JMS\Serializer\Annotation\SerializedName('step_details')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $stepDetails;
    
    /**
     * The ID of the [thread](/docs/api-reference/threads) that was run.
     * 
     * @var string $threadId
     */
	#[\JMS\Serializer\Annotation\SerializedName('thread_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $threadId;
    
    /**
     * The type of run step, which can be either `message_creation` or `tool_calls`.
     * 
     * @var \Openai\SDK\Models\Shared\RunStepObjectType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\RunStepObjectType>')]
    public RunStepObjectType $type;
    
	public function __construct()
	{
		$this->assistantId = "";
		$this->cancelledAt = 0;
		$this->completedAt = 0;
		$this->createdAt = 0;
		$this->expiredAt = 0;
		$this->failedAt = 0;
		$this->id = "";
		$this->lastError = new \Openai\SDK\Models\Shared\RunStepObjectLastError();
		$this->metadata = new \Openai\SDK\Models\Shared\RunStepObjectMetadata();
		$this->object = \Openai\SDK\Models\Shared\RunStepObjectObject::AssistantRunStep;
		$this->runId = "";
		$this->status = \Openai\SDK\Models\Shared\RunStepObjectStatus::InProgress;
		$this->stepDetails = null;
		$this->threadId = "";
		$this->type = \Openai\SDK\Models\Shared\RunStepObjectType::MessageCreation;
	}
}
