<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The type of tool call the output is required for. For now, this is always `function`. */
enum RunToolCallObjectType: string
{
    case Function = 'function';
}
