<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/**
 * RunToolCallObject - Tool call objects
 * 
 * @package Openai\SDK\Models\Shared
 * @access public
 */
class RunToolCallObject
{
    /**
     * The function definition.
     * 
     * @var \Openai\SDK\Models\Shared\RunToolCallObjectFunction $function
     */
	#[\JMS\Serializer\Annotation\SerializedName('function')]
    #[\JMS\Serializer\Annotation\Type('Openai\SDK\Models\Shared\RunToolCallObjectFunction')]
    public RunToolCallObjectFunction $function;
    
    /**
     * The ID of the tool call. This ID must be referenced when you submit the tool outputs in using the [Submit tool outputs to run](/docs/api-reference/runs/submitToolOutputs) endpoint.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The type of tool call the output is required for. For now, this is always `function`.
     * 
     * @var \Openai\SDK\Models\Shared\RunToolCallObjectType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<Openai\SDK\Models\Shared\RunToolCallObjectType>')]
    public RunToolCallObjectType $type;
    
	public function __construct()
	{
		$this->function = new \Openai\SDK\Models\Shared\RunToolCallObjectFunction();
		$this->id = "";
		$this->type = \Openai\SDK\Models\Shared\RunToolCallObjectType::Function;
	}
}
