<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class ToolOutputs
{
    /**
     * The output of the tool call to be submitted to continue the run.
     * 
     * @var ?string $output
     */
	#[\JMS\Serializer\Annotation\SerializedName('output')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $output = null;
    
    /**
     * The ID of the tool call in the `required_action` object within the run object the output is being submitted for.
     * 
     * @var ?string $toolCallId
     */
	#[\JMS\Serializer\Annotation\SerializedName('tool_call_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $toolCallId = null;
    
	public function __construct()
	{
		$this->output = null;
		$this->toolCallId = null;
	}
}
