<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


class TopLogprobs
{
    /**
     * A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
     * 
     * @var array<int> $bytes
     */
	#[\JMS\Serializer\Annotation\SerializedName('bytes')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    public array $bytes;
    
    /**
     * The log probability of this token.
     * 
     * @var float $logprob
     */
	#[\JMS\Serializer\Annotation\SerializedName('logprob')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $logprob;
    
    /**
     * The token.
     * 
     * @var string $token
     */
	#[\JMS\Serializer\Annotation\SerializedName('token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $token;
    
	public function __construct()
	{
		$this->bytes = [];
		$this->logprob = 0;
		$this->token = "";
	}
}
