<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Openai\SDK\Models\Shared;


/** The voice to use when generating the audio. Supported voices are `alloy`, `echo`, `fable`, `onyx`, `nova`, and `shimmer`. Previews of the voices are available in the [Text to speech guide](/docs/guides/text-to-speech/voice-options). */
enum Voice: string
{
    case Alloy = 'alloy';
    case Echo = 'echo';
    case Fable = 'fable';
    case Onyx = 'onyx';
    case Nova = 'nova';
    case Shimmer = 'shimmer';
}
