name: Generate
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      force: ${{ github.event.inputs.force }}
      languages: '- php'
      mode: pr
      openapi_doc_location: https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml
      publish_php: true
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      packagist_token: ${{ secrets.PACKAGIST_TOKEN }}
      packagist_username: ${{ secrets.PACKAGIST_USERNAME }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
