name: Generate

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * * # Runs every day at midnight

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v13
    with:
      speakeasy_version: latest
      openapi_doc_location: https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml
      languages: |-
        - php: ./
      publish_php: true
      force: ${{ github.event.inputs.force }} 
      mode: pr
    secrets:
      packagist_username: ${{ secrets.PACKAGIST_USERNAME }}
      packagist_token: ${{ secrets.PACKAGIST_TOKEN }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
